# Generated by Django 3.2.12 on 2022-02-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='available',
            field=models.BooleanField(null=True),
        ),
    ]
