# Generated by Django 3.2.12 on 2022-02-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_hotels_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
